### ISSUE TITLE
Bug if several search company in a row

### ISSUE THREAD

**Issue by olivierreberga** [tomquirk/linkedin-api#88] opened 2020-04-11 17:10 UTC
If I perform several search company with code below, there is a bug, the method returns alway the first company:

```
linkedin = Linkedin('XX', 'XX',
					authenticate=True,
					refresh_cookies=False,
					debug=True,
					)

companies = ['facebook', 'google', 'tesla', 'amazon', 'apple']

for c in companies:
	print(c)
	results = linkedin.search_companies(
	  keywords=c,
		limit=3
	)

	print(results)
```
It returns 5 times:

`[{'urn': 'urn:li:fs_miniCompany:10667', 'urn_id': '10667', 'name': 'Facebook', 'headline': 'Internet', 'subline': '10,001+ employees'}, {'urn': 'urn:li:fs_miniCompany:2269767', 'urn_id': '2269767', 'name': 'Facebook Apps World', 'headline': 'Internet', 'subline': '11-50 employees'}, {'urn': 'urn:li:fs_miniCompany:2226401', 'urn_id': '2226401', 'name': 'Facebook Advertising', 'headline': 'Marketing and Advertising', 'subline': '1-10 employees'}]`

**Comment by tomquirk** [comment] 2020-04-27 21:15
Closing as duplicate of https://github.com/tomquirk/linkedin-api/issues/74 (if it's not, please reopen this!)

**Comment by olivierreberga** [comment] 2020-05-21 07:04
No, this is not the same issue, in my case, I'm looking for 3 companies: AAA, BBB, CCC with 3 searches (loop). What I get in return is the search result for AAA, AAA, AAA.

I've fixed locally the issue, in `linkedin.py` and  `search_companies` line 201, I'm forcing the `result` reinit by replacing:

`data = self.search(params, limit=limit)`

by

`data = self.search(params, limit=limit, results=[])  # Don't forget to init results`

And it works fine. I've also done that for `search_people`

**Comment by tomquirk** [comment] 2020-06-21 00:35
@olivierreberga I just pushed a potential fix for this. Can you have a look and see if it resolved your issue?

**Comment by tomquirk** [comment] 2020-08-04 00:14
I'm assuming this has been fixed. Closing issue! Please reopen and tag me if you are still having problems.

**Closed by tomquirk** 2020-08-04 00:14 UTC
Labels: bug
