### ISSUE TITLE
Error consuming service with no json returned

### ISSUE THREAD

**Issue by adgonzalez021091** [tomquirk/linkedin-api#111] opened 2020-08-18 17:18 UTC
Hi!... First of all, I´m really grateful for your library, it is really helpful and easy to use. I am trying to reach some data but since last friday it is returning the next error from consumes that returned ok in the past.

  File "/Users/alvarogonzalez/opt/anaconda3/lib/python3.7/site-packages/linkedin_api/linkedin.py", line 349, in get_profile
    data = res.json()

  File "/Users/alvarogonzalez/opt/anaconda3/lib/python3.7/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)

  File "/Users/alvarogonzalez/opt/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)

  File "/Users/alvarogonzalez/opt/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/Users/alvarogonzalez/opt/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value

Thanks in advance and I hope that is not something I´m doing wrong :)

**Comment by keducoop** [comment] 2020-08-30 16:36
Hi @adgonzalez021091 , could you please add a snippet to try reproducing the issue?

Otherwise I'm afraid it's almost impossible to help.

Many thanks.

**Comment by abinpaul1** [comment] 2022-01-03 11:38
Closing due to insufficient information. Feel free to reopen with the necessary new information.

**Closed by abinpaul1** 2022-01-03 11:38 UTC
Labels: bug, needs investigation
