### ISSUE TITLE
AttributeError: 'Linkedin' object has no attribute 'add_connection'

### ISSUE THREAD

**Issue by mhmzdev** [tomquirk/linkedin-api#192] opened 2021-11-20 06:50 UTC
I'm using latest version of `linkedin-api` yet I'm getting this error:

### ERROR:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-68dfe11587c3> in <module>
      1 # for user in search_ppl:
----> 2 api.add_connection(profile_public_id='user-profile-here', message='some message here')

AttributeError: 'Linkedin' object has no attribute 'add_connection'
```

After running `pip show linkedin-api`
```
Name: linkedin-api
Version: 2.0.0a5
Summary: Python wrapper for the Linkedin API
Home-page: https://github.com/tomquirk/linkedin-api
Author: Tom Quirk
Author-email: tomquirkacc@gmail.com
License: MIT
Location: c:\users\hamza\appdata\local\programs\python\python39\lib\site-packages
Requires: beautifulsoup4, requests, lxml
Required-by: 
```

### CODE:
```python
api.add_connection(profile_public_id='user-profile-here', message='some message here')
```

**Comment by abinpaul1** [comment] 2021-11-22 15:08
The latest pypi release is a year old. 
To get the latest development release try installing like
`pip install git+https://github.com/tomquirk/linkedin-api.git`.
This should get you all the newly added methods

**Comment by abinpaul1** [comment] 2022-01-03 11:15
Closing for now. Feel free to reopen if needed.

**Closed by abinpaul1** 2022-01-03 11:15 UTC

**Comment by arm-on** [comment] 2022-03-19 20:21
> abinpaul1

Dude! The problem still exists! I'm using 2.0.0a5 and I get the same error! 
Please write the definition of the "add_connection" function if you have it!

**Comment by abinpaul1** [comment] 2022-03-20 04:06
2.0.0a5 does not have the latest changes including the add_connection. As mentioned in above comment install the library from this repo. `pip install git+https://github.com/tomquirk/linkedin-api.git`

**Comment by arm-on** [comment] 2022-03-20 06:27
> 2.0.0a5 does not have the latest changes including the add_connection. As mentioned in above comment install the library from this repo. `pip install git+https://github.com/tomquirk/linkedin-api.git`

I used exactly the same command to install the package. However, by default it installs 2.0.0a5. How can I change it? More precisely, which version should be installed?

**Comment by abinpaul1** [comment] 2022-03-20 06:49
The version code in pypi and the repo are the same and hence its not getting updated in your case. You would have to maybe force install the repo version. You could try something like `pip install --upgrade --no-deps --force-reinstall git+https://github.com/tomquirk/linkedin-api.git`

**Comment by arm-on** [comment] 2022-03-20 22:55
> The version code in pypi and the repo are the same and hence its not getting updated in your case. You would have to maybe force install the repo version. You could try something like `pip install --upgrade --no-deps --force-reinstall git+https://github.com/tomquirk/linkedin-api.git`

Thanks :) I just uninstalled the package and reinstalled it. The problem is solved :)
