### ISSUE TITLE
search_people or search always returns same first result that found something

### ISSUE THREAD

**Issue by woutwoot** [tomquirk/linkedin-api#64] opened 2019-09-23 10:20 UTC
When calling search_people or search multiple times, as soon as there is a result these methods will keep returning that same result for all subsequent searches.

**Comment by tomquirk** [comment] 2019-09-24 01:36
wow, if I understand what you're saying, thats whack. Would you be able to provide an example? Search_people is clearly broken (see other issues) so I'll look into fixing it soon

**Comment by woutwoot** [comment] 2019-09-24 06:59
Sure. This already works as a test:
```from linkedin_api import Linkedin


TEST_NAMES = ['Bill Gates', 'Mark Zuckerberg']

api = Linkedin('***', "***")

for name in TEST_NAMES:
    print(api.search_people(name, limit=2))
```

Will print:
```
[{'urn_id': 'ACoAAA8BYqEBCGLg_vT_ca6mMEqkpp9nVffJ3hc', 'distance': 'OUT_OF_NETWORK', 'public_id': 'williamhgates'}, {'urn_id': 'ACoAAAAsx6sBC0HzA1cBh8j5_s7XP9W4dihhppE', 'distance': 'DISTANCE_2', 'public_id': 'billbrindley'}]
[{'urn_id': 'ACoAAA8BYqEBCGLg_vT_ca6mMEqkpp9nVffJ3hc', 'distance': 'OUT_OF_NETWORK', 'public_id': 'williamhgates'}, {'urn_id': 'ACoAAAAsx6sBC0HzA1cBh8j5_s7XP9W4dihhppE', 'distance': 'DISTANCE_2', 'public_id': 'billbrindley'}]
```

**Comment by tomquirk** [comment] 2019-09-24 08:11
lmao, thanks for that @woutwoot . Very interesting...

**Comment by woutwoot** [comment] 2019-09-30 10:55
Any news on this? Could probably try to take a look myself, but doubt I'll find the cause quickly. Might be possible that LinkedIn is just returning the same thing?

**Comment by tomquirk** [comment] 2019-10-04 12:28
Yea it's a tough one. The only difference I see between search requests is this header:
```
```

**Comment by LouisBellinger** [comment] 2019-11-15 09:55
Hello. I'm facing this bothering issue as well. Any update?

**Comment by naiktanmai** [comment] 2020-03-11 08:33
@LouisBellinger think adding  `"Cache-Control"` : `"no-cache"` to https://github.com/tomquirk/linkedin-api/blob/master/linkedin_api/client.py#L34 worked for me.

**Comment by nikalexo** [comment] 2020-04-27 11:58
After 2 days of investigation I found out the the problem has nothing to do with the response, rather with how python handles default variables (see: http://effbot.org/zone/default-values.htm).

In short, default variables are only evaluated when the `def` statement is executed, resulting in the following whacky behavior in https://github.com/tomquirk/linkedin-api/blob/449d4699e5fcb759a58e5ac3cd7e3a8e3f6a1fb3/linkedin_api/linkedin.py#L73 The results list is initiated once when the object is created and then results are appended to it (since lists are mutable). Now, these results are always trimmed, so the results of the very first query are returned!! A quick work-around would be to always call search with a results argument, until the issue is resolved in the code, e.g. to fix `search_people`, change https://github.com/tomquirk/linkedin-api/blob/449d4699e5fcb759a58e5ac3cd7e3a8e3f6a1fb3/linkedin_api/linkedin.py#L171 to         `data = self.search(params, limit=limit, results=[])` .

Also, the recursion is problematic leading to infinite loops when e.g. you request 2 results (limit=2) but only 1 is returned. Since all of the above are just dirty work-arounds, I am not submitting any patches. If I find a bit of time in the future, I could try to write some.

**Comment by olivierreberga** [comment] 2020-05-21 07:11
Yes, agree with you @nikalexo, I've applied the same fix, and this needs to be fixed in `search_companies` as well

**Comment by tomquirk** [comment] 2020-06-21 00:36
@olivierreberga @nikalexo @woutwoot I just pushed a potential fix for this. Can you have a look and see if it resolved your issue?

**Comment by tomquirk** [comment] 2020-08-04 00:16
I'm assuming this has been fixed. Closing issue! Please reopen and tag me if you are still having problems.

**Closed by tomquirk** 2020-08-04 00:16 UTC
Labels: bug
